apiVersion: v1
kind: Secret
metadata:
  name: dev-secret-one
  namespace: dev
type: kubernetes.io/ssh-auth
data:
  # the data is abbreviated in this example
  ssh-privatekey: 'UG91cmluZzYlRW1vdGljb24lU2N1YmE='

---
apiVersion: v1
kind: Secret
metadata:
  name: dev-secret-two
  namespace: dev
type: kubernetes.io/ssh-auth
data:
  privatekey-dev: 'UG91cmluZzYlRW1vdGljb24lU2N1YmE='
  ssh-privatekey: 'UG91cmluZzYlRW1vdGljb24lU2N1YmE='